name: main

on:
  workflow_dispatch: {}
  pull_request: {}
  label:
    types: [created]

jobs:
  job1:
    uses: ./.github/workflows/sub.yml
    secrets: inherit
    steps:
    - name: additional
      run: echo foo


  job2:
    if: contains(github.event.pull_request.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
