name: sub

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        env:
          F: ${{ secrets.FOO }}
        run: |
          set -x
          echo $F
          echo $BAR
